 #Config mặc định CHUNG cho toàn bộ project
# Các file config yaml khác sẽ inherit thằng này
# Và ghi đè lại, chỉ ghi đè F1, không ghi đè F0!
# ----------- ----------- -----------

data:
  name: "fer13-split"
  num_classes: 7  # 1-angry, 2-disgust, 3-fear, 4-happy, 5-neutral, 6-sad, 7-surprise
  image_size: 48  # Q thấy dataset gốc:O 48x48
  batch_size: 64
  num_workers: 2  # num_workers is the number of subprocesses to use for data loading. 

seed: 
  random_seed: 42

model:
  name: "simple_cnn"       # Tên model (key trong registry)
  pretrained: False        # Sử dụng pretrain model hông?

training:
  epochs: 101
  patience: 10
  weight_decay: 0.0001
  loss: 'cross_entropy'
  optimizer: "adam"       # adam(*) | sgd 
  lr: 0.001
  scheduler: "reduce_lr_on_plateau"  # none | step | cosine | reduce_lr_on_plateau (*)


# !!! WARNING !!!  
logging:
  # wandb
  use_wandb: False
  wandb_entity: "phucga15062005"
  wandb_project: "FER2013"
  # save_dir_name: "outputs"
  
# !!! WARNING !!!  
env:
  platform: "kaggle"         # local | kaggle

# !!! WARNING !!!  
kaggle:
  data_path: "/kaggle/input/datasets/doduyquynii/fer13-split/fer13-split" # double fer13-split
  root_path: "/kaggle/working/sgu-2026-facial-expression-recognition"

local:
  data_path: '...'
  root_path: '...'
  # hi, guy, your path