_base_: "convnext_tiny_mask_guided_region_attention_imagenet_sam_continue.yaml"

model:
  mask_dir: "/kaggle/input/fer2013-mediapipe-region-masks/mediapipe_region_masks"

data:
  mask_dir: "/kaggle/input/fer2013-mediapipe-region-masks/mediapipe_region_masks"
