model:
  name: "motif_graph_fer"
  in_channels: 3
  pretrained_cnn_path: "/kaggle/input/datasets/lhngphc/resnet152-0-73/resnet152_rot30_2019Nov14_12.47" # ""
  feat_dim: 128
  num_classes: 7
  motifs_per_class: 16
  top_k: 6
  offset_amplitude: 0.35
  dropout: 0.3

data:
  batch_size: 64
  num_workers: 4
  input_size: 224
  in_channels: 3

training:
  epochs: 1000
  lr: 0.0001
  backbone_lr_mult: 0.1
  mixup_alpha: 0.2
  weight_decay: 5e-4
  loss: "sce"
  label_smoothing: 0.2
  class_weight_mode: "sqrt_inverse"
  motif_consistency_weight: 0.05
  motif_diversity_weight: 0.05
  attn_entropy_weight: 0.01
  offset_reg_weight: 0.01
  motif_tau: 0.2
  scheduler: "reduce_lr_on_plateau"
  patience: 25
  lr_patience: 4
  lr_factor: 0.5