_base_: "base.yaml"

model:
  name: "resnet"
  pretrained: false



training:
  epochs: 200
  patience: 10
  loss: "cross_entropy"
  focal_gamma: 2.0
  optimizer: "adam"
  lr: 0.0003
  weight_decay: 0.0001

  scheduler: "reduce_lr_on_plateau"
  lr_factor: 0.5
  lr_patience: 3