_base_: "base.yaml"

model:
  name: "resnet35"
  attention_type: "cbam"  
  attention_kernel_size: 3

data:
  image_size: 48
  channels: 1             # 1 for grayscale (FER2013)
  batch_size: 64

training:
  lr: 0.001
  epochs: 100
  optimizer: "adamw"
  weight_decay: 0.01
  label_smoothing: 0.1
  scheduler: "reduce_lr_on_plateau"
  lr_patience: 5
  lr_factor: 0.5
  use_class_weights: true # Bật tính năng Class Weights