_base_: "base.yaml"

model:
  name: "resnet35"
  attention_type: "cbam"

data:
  image_size: 48
  channels: 1
  batch_size: 64

training:
  loss: "focal"
  focal_gamma: 2.0
  focal_use_class_weights: true
  lr: 0.0007
  epochs: 100
  optimizer: "adamw"
  weight_decay: 0.001
  scheduler: "reduce_lr_on_plateau"
  lr_patience: 7
  lr_factor: 0.5
  use_class_weights: true

logging:
  wandb_run_name: "resnet35_cbam_focal"
