_base_: "base.yaml"

data:
  use_landmarks: false

model:
  name: "resnet"
  pretrained: false
  use_landmark_cross_fusion: true
  use_pyramid_multi_scale: true
  img_topk_tokens: 49
  token_selection_mode: "topk_softmax"
  use_sinusoidal_pos: true
  pyramid_dropout_rate: 0.1
  pyramid_depth: 4
  cross_attn_dim: 256
  cross_attn_heads: 8
  use_token_conv_mix: true
  landmark_token_mode: "learnable"  # learnable | input | hybrid

training:
  epochs: 200
  patience: 10
  loss: "cross_entropy"
  use_class_weights: False
  class_weight_mode: "sqrt_inverse"
  optimizer: "adam"
  lr: 0.0003
  weight_decay: 0.0001
  scheduler: "reduce_lr_on_plateau"
  lr_factor: 0.5
  lr_patience: 3
