
# Kế thừa base & override cho VGG
_base_: "base.yaml"             # Kế thừa từ base

model:
  name: "vgg19"
  pretrained: true      # chuyển sang dùng pretrained
  dropout_block: 0.3    # Tỉ lệ dropout trong các Conv Blocks (giúp giảm overfitting)
  dropout_dense: 0.5    # Tỉ lệ dropout trong lớp Fully Connected cuối cùng

data:
  image_size: 224        # FER2013 gốc là 48x48. Nếu bạn muốn resize lên 224 thì chỉnh ở đây.
  channels: 3            # 1: kịch bản 1 kênh, 3: kịch bản 3 kênh
  batch_size: 32        # Tùy vào GPU (VRAM), nếu bị lỗi Out of Memory thì giảm xuống 16 hoặc 8.

training:
  lr: 0.0001             # Giảm LR xuống 10 lần cho fine-tuning
  epochs: 30            # Số vòng lặp tập huấn.
