# VGG Fusion (Multi-Scale) for 48x48 grayscale input
_base_: "base.yaml"

model:
  name: "vgg_spatial"
  use_aux: true # Bật nhánh phụ (auxiliary branch) để ổn định training
  use_attention: true # Bật cơ chế Spatial Attention
  dropout_block: 0.3
  dropout_dense: 0.5

data:
  image_size: 48
  channels: 1 
  batch_size: 64
  # mean: [0.5077]
  # std: [0.2550]
training:
  use_class_weights: true # Bật tính năng Class Weights
  lr: 0.0005 # Giảm LR xuống một nửa để học mịn hơn (5e-4)
  epochs: 100
  patience: 20 # Giảm patience xuống 20 (vì sau đó thường đã overfit)
  label_smoothing: 0.1 # Thêm Label Smoothing để model bền vững với nhiễu
  loss: "cross_entropy" 
