# VGG Spatial Attention + Fusion (CNN Only) - HIGH RES 6x6
_base_: "vgg_spatial_fusion.yaml"

model:
  name: "vgg_spatial"
  high_res: true      # Bật chế độ 6x6
  dropout_dense: 0.6  # Tăng dropout vì số lượng tham số tăng lên nhiều
  use_aux: true

training:
  lr: 0.0001
  epochs: 100
  batch_size: 48      # Giảm batch size một chút đề phòng tốn VRAM
data:
  mean: [0.5077]
  std: [0.2550]